<p estilo="text-align:centro">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Logotipo de Skills Network">
    </a>
</p>

# **Predicción del aterrizaje de la primera etapa del Space X Falcon 9**

## Laboratorio 2: manipulación de datos

Tiempo estimado necesario: **60** minutos

En esta práctica de laboratorio, realizaremos un análisis de datos exploratorios (EDA) para encontrar algunos patrones en los datos y determinar cuál sería la etiqueta para entrenar modelos supervisados. 

En el conjunto de datos, hay varios casos diferentes en los que el propulsor no aterrizó con éxito. A veces se intentó un aterrizaje pero fracasó debido a un accidente; por ejemplo, <code>True Ocean</code> significa que el resultado de la misión aterrizó con éxito en una región específica del océano, mientras que <code>False Ocean</code> significa que el resultado de la misión aterrizó sin éxito en una región específica del océano. <code>RTLS verdadero</code> significa que el resultado de la misión aterrizó exitosamente en una plataforma terrestre. <code>RTLS falso</code> significa que el resultado de la misión no aterrizó exitosamente en una plataforma terrestre. <code>ASDS verdadero</code> significa que el resultado de la misión se aterrizó exitosamente en un barco no tripulado. <code>ASDS falso</code> significa que el resultado de la misión se aterrizó sin éxito en un barco no tripulado. 

En esta práctica de laboratorio, convertiremos principalmente esos resultados en etiquetas de entrenamiento. "1" significa que el refuerzo aterrizó exitosamente. "0" significa que no tuvo éxito.

La primera etapa del Falcon 9 aterrizará con éxito

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/landing_1.gif)

A continuación se muestran varios ejemplos de un aterrizaje fallido:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/crash.gif)

## Objetivos
Realizar análisis de datos exploratorios y determinar etiquetas de capacitación 

- Análisis de datos exploratorios
- Determinar etiquetas de entrenamiento

Instale las siguientes bibliotecas

In [ ]:
!pip install pandas
!pip install numpy

## Importar bibliotecas y definir funciones auxiliares

Importaremos las siguientes bibliotecas.

In [1]:
# Pandas es una biblioteca de software escrita para el lenguaje de programación Python para la manipulación y análisis de datos.
import pandas as pd
# NumPy es una biblioteca para el lenguaje de programación Python, que agrega soporte para matrices y arreglos multidimensionales grandes, junto con una gran colección de funciones matemáticas de alto nivel para operar en estos arreglos.
import numpy as np

### Análisis de datos

Cargue el conjunto de datos de Space X, de la última sección.

In [2]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

Identificar y calcular el porcentaje de los valores faltantes en cada atributo.

In [3]:
df.isnull().sum()/len(df)*100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

Identifique qué columnas son numéricas y categóricas:

In [4]:
df.dtypes

FlightNumber        int64
Date                  str
BoosterVersion        str
PayloadMass       float64
Orbit                 str
LaunchSite            str
Outcome               str
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad            str
Block             float64
ReusedCount         int64
Serial                str
Longitude         float64
Latitude          float64
dtype: object

### TAREA 1: Calcular el número de lanzamientos en cada sitio

Los datos contienen varias instalaciones de lanzamiento de Space X: <a href='https://en.wikipedia.org/wiki/List_of_Cape_Canaveral_and_Merritt_Island_launch_sites'>Cape Canaveral Space</a> Launch Complex 40 <b>VAFB SLC 4E </b>, Vandenberg Air Force Base Space Launch Complex 4E <b>(SLC-4E)</b>, Kennedy Space Center Launch Complex 39A <b>KSC LC 39A </b>. La ubicación de cada lanzamiento se coloca en la columna <code>LaunchSite</code>

A continuación, veamos la cantidad de lanzamientos de cada sitio.

Utilice el método <code>value_counts()</code> en la columna <code>LaunchSite</code> para determinar el número de lanzamientos en cada sitio:

In [9]:
print(f'Nº de lanzamientos: \n{df['LaunchSite'].value_counts()}')

Nº de lanzamientos:
LaunchSite
CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

Cada lanzamiento apunta a una órbita dedicada y estos son algunos tipos de órbitas comunes:

* <b>LEO</b>: La órbita terrestre baja (LEO) es una órbita centrada en la Tierra con una altitud de 2000 km (1200 millas) o menos (aproximadamente un tercio del radio de la Tierra),[1] o con al menos 11,25 períodos por día (un período orbital de 128 minutos o menos) y una excentricidad inferior a 0,25.[2] La mayoría de los objetos creados por el hombre en el espacio exterior se encuentran en LEO <a href='https://en.wikipedia.org/wiki/Low_Earth_orbit'>[1]</a>.

* <b>VLEO</b>: Las órbitas terrestres muy bajas (VLEO) se pueden definir como órbitas con una altitud media inferior a 450 km. Operar en estas órbitas puede proporcionar una serie de beneficios a las naves espaciales de observación de la Tierra, ya que la nave espacial opera más cerca del lugar de observación<a href='https://www.researchgate.net/publication/271499606_Very_Low_Earth_Orbit_mission_concepts_for_Earth_Observation_Benefits_and_challenges'>[2]</a>.


* <b>GTO</b>(Órbita de transferencia geoestacionaria): una órbita de transferencia geoestacionaria es una órbita terrestre elíptica que se utiliza para transferir satélites desde la órbita terrestre baja (LEO) a la órbita geoestacionaria (GEO). En un GTO, el perigeo (punto más cercano a la Tierra) es mucho menor que la altitud GEO, mientras que el apogeo (punto más lejano) alcanza aproximadamente 22,236 millas (35,786 kilómetros) sobre el ecuador de la Tierra, la altitud de una órbita geoestacionaria. Los satélites en GTO utilizan propulsión a bordo para circular su órbita a altitud GEO, donde pueden proporcionar servicios como monitoreo meteorológico, comunicaciones y vigilancia. <a href="https://www.space.com/29222-geosynchronous-orbit.html" >[3] </a>.


* <b>SSO (o SO)</b>: Es una órbita sincrónica con el Sol, también llamada órbita heliosincrónica, es una órbita casi polar alrededor de un planeta, en la que el satélite pasa sobre cualquier punto dado de la superficie del planeta a la misma hora solar media local <a href="https://en.wikipedia.org/wiki/Sun-synchronous_orbit">[4] <a>.
    
    
    
* <b>ES-L1 </b>:En los puntos de Lagrange las fuerzas gravitacionales de los dos cuerpos grandes se anulan de tal manera que un objeto pequeño colocado en órbita allí está en equilibrio con respecto al centro de masa de los cuerpos grandes. L1 es uno de esos puntos entre el sol y la tierra <a href="https://en.wikipedia.org/wiki/Lagrange_point#L1_point">[5]</a>.
    
    
* <b>HEO</b> Una órbita altamente elíptica, es una órbita elíptica con alta excentricidad, generalmente refiriéndose a una alrededor de la Tierra <a href="https://en.wikipedia.org/wiki/Highly_elliptical_orbit">[6]</a>.


* <b> ISS </b> Una estación espacial modular (satélite artificial habitable) en órbita terrestre baja. Es un proyecto de colaboración multinacional entre cinco agencias espaciales participantes: NASA (Estados Unidos), Roscosmos (Rusia), JAXA (Japón), ESA (Europa) y CSA (Canadá)<a href="https://en.wikipedia.org/wiki/International_Space_Station"> [7] </a>


* <b> MEO </b> Órbitas geocéntricas que varían en altitud desde 2000 km (1200 millas) hasta justo debajo de la órbita geosincrónica a 35 786 kilómetros (22 236 millas). También conocida como órbita circular intermedia. Estos están "más comúnmente a 20.200 kilómetros (12.600 millas) o 20.650 kilómetros (12.830 millas), con un período orbital de 12 horas <a href="https://en.wikipedia.org/wiki/List_of_orbits"> [8] </a>


* <b> HEO </b> Órbitas geocéntricas por encima de la altitud de la órbita geosincrónica (35 786 km o 22 236 mi) <a href="https://en.wikipedia.org/wiki/List_of_orbits"> [9] </a>


* <b> GEO </b> Es una órbita geosincrónica circular a 35.786 kilómetros (22.236 millas) sobre el ecuador de la Tierra y que sigue la dirección de rotación de la Tierra <a href="https://en.wikipedia.org/wiki/Geostationary_orbit"> [10] </a>


* <b> PO </b> Es un tipo de satélites en los que un satélite pasa por encima o casi por encima de ambos polos del cuerpo que está en órbita (normalmente un planeta como la Tierra <a href="https://en.wikipedia.org/wiki/Polar_orbit"> [11] </a>

algunos se muestran en el siguiente gráfico:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/api/Images/Orbits.png)

### TAREA 2: Calcular el número y la aparición de cada órbita

Utilice el método <code>.value_counts()</code> para determinar el número y la aparición de cada órbita en la columna <code>Orbit</code>


Nota: No cuente GTO, ya que es una órbita de transferencia y no geoestacionaria en sí misma.

In [22]:
print(f'Nº de lanzamientos en cada orbita: \n{df['Orbit'].value_counts().drop('GTO')}')

Nº de lanzamientos en cada orbita:
Orbit
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
ES-L1     1
HEO       1
SO        1
GEO       1
Name: count, dtype: int64

### TAREA 3: Calcular el número y la ocurrencia del resultado de la misión de las órbitas

Utilice el método <code>.value_counts()</code> en la columna <code>Outcome</code> para determinar el número de <code>landing_outcomes</code>. Luego asígnelo a una variable landing_outcomes.

In [36]:
landing_outcomes = df.Outcome.value_counts()
landing_outcomes

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

<code>True Ocean</code> significa que el resultado de la misión aterrizó con éxito en una región específica del océano, mientras que <code>False Ocean</code> significa que el resultado de la misión aterrizó sin éxito en una región específica del océano. <code>RTLS verdadero</code> significa que el resultado de la misión aterrizó exitosamente en una plataforma terrestre. <code>RTLS falso</code> significa que el resultado de la misión no aterrizó exitosamente en una plataforma terrestre. <code>ASDS verdadero</code> significa que el resultado de la misión se aterrizó exitosamente en un barco no tripulado. <code>ASDS falso</code> significa que el resultado de la misión se aterrizó sin éxito en un barco no tripulado. <code>Ninguno ASDS</code> y <code>Ninguno Ninguno</code> representan un fracaso en el aterrizaje.

In [27]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

Creamos un conjunto de resultados donde la segunda etapa no aterrizó con éxito:

In [29]:
bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

### TAREA 4: Crear una etiqueta de resultado de aterrizaje a partir de la columna Resultado

Usando <code>Resultado</code>, cree una lista donde el elemento sea cero si la fila correspondiente en <code>Resultado</code> está en el conjunto <code>bad_outcome</code>; de lo contrario, es uno. Luego asígnalo a la variable <code>landing_class</code>:

In [31]:
# landing_class = 0 si mal_resultado
# landing_class = 1 en caso contrario
landing_class = df.Outcome.map(lambda x: 0 if x in bad_outcomes else 1).values

Esta variable representará la variable de clasificación que representa el resultado de cada lanzamiento. Si el valor es cero, la primera etapa no aterrizó exitosamente; uno significa que la primera etapa aterrizó con éxito

In [32]:
df['Class']=landing_class
df[['Class']].head(8)

   Class
0      0
1      0
2      0
3      0
4      0
5      0
6      1
7      1

In [33]:
df.head(5)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0

Podemos utilizar la siguiente línea de código para determinar la tasa de éxito:

In [34]:
df["Class"].mean()

np.float64(0.6666666666666666)

Ahora podemos exportarlo a un CSV para la siguiente sección, pero para que las respuestas sean consistentes, en la próxima práctica de laboratorio proporcionaremos datos en un rango de fechas preseleccionado.

In [35]:
df.to_csv("dataset_part_2.csv", index=False)